apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: sno/operators
    repoURL: 'https://github.com/cainza/sno-openshift-demo-environment'
    targetRevision: HEAD