apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  finalizers:
  - kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb-rhacs
  namespace: rhacs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
